# WDP Custom Items Config
beam-sword:
  damage: 15
  knockback: 3
  cooldown: 5.0
  color: RED # default color
  short-cooldown: 1.0 # If nothing gets hit
  speed: 1 # Ticks between next step: step = distance / particle (50)
  range: 50.0 # Distance

grappling-hook:
  short-cooldown: 1.0 # Invalid, using beam-sword.short cooldown
  cooldown: 5.0
