name: WDP_Custom_Items
main: com.wdpserver.wdpcustomitems.WdpCustomItems
version: 1.0
api-version: 1.20
commands:
  givesword:
    description: Gives a custom beam sword
  reloadconfig:
    description: Reloads the plugin config
